apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: d01
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
